### ISSUE TITLE
Add Basic resources for a Portfolio Template

### ISSUE THREAD

**Issue by m-faraz-ali** [Faraz1243/OpenSourse-Static-Web-Templates#20]
Make sure to upload all the files inside the folder named personal portfolio

**Comment by ashucoder1** [comment]
assign me this ,i have a template to add(frontend)

**Comment by m-faraz-ali** [comment]
Asu

> assign me this ,i have a template to add(frontend)

kindly make another folder for that

**Comment by WaqasAly** [comment]
I am also interested ( meet you in class today ).
