### ISSUE TITLE
Pre Order Traversal

### ISSUE THREAD

**Issue by m-faraz-ali** [Faraz1243/OpenSourse-Static-Web-Templates#44]

**Comment by niteshjeganathan** [comment]
Hey, Can you please assign this to me

**Comment by Hrithik4579** [comment]
hey! can you please assign this task to me?

**Comment by kushagra10bansal** [comment]
hey! @Faraz1243 can you please assign this task to me?

**Comment by niteshjeganathan** [comment]
@m-faraz-ali I have uploaded the code for pre order at #65. Please accept my PR.
