### ISSUE TITLE
Post Order Traversal

### ISSUE THREAD

**Issue by m-faraz-ali** [Faraz1243/OpenSourse-Static-Web-Templates#45]
Add the C++ traversal code in the C++ file with commenting

**Comment by VarnikaB** [comment]
Can you assign this to me

**Comment by niteshjeganathan** [comment]
Hey, can you please assign this to me

**Comment by Hrithik4579** [comment]
hey! can you please assign this task to me?

**Comment by Saloni2004** [comment]
Hey,please assign me this
