### ISSUE TITLE
max funtion

### ISSUE THREAD

**Issue by m-faraz-ali** [Faraz1243/OpenSourse-Static-Web-Templates#47]
function to find max of 2 integers

**Comment by Yasir-Mahmood-124** [comment]
I will do that.

**Comment by niteshjeganathan** [comment]
Hey, can you please assign this to me.

**Comment by hamzabohra** [comment]
can i work on this?

**Comment by vaibhv232** [comment]
assign me this issue

**Comment by hamzabohra** [comment]
i want to work on this issue. plz assign it to me!!
