### ISSUE TITLE
add to a binary search tree

### ISSUE THREAD

**Issue by Yasir-Mahmood-124** [Faraz1243/OpenSourse-Static-Web-Templates#54]

**Comment by Ash0069** [comment]
Hi @Faraz1243, please assign this to me

**Comment by Hrithik4579** [comment]
hey! @Faraz1243 could you please describe and assign me this task?

**Comment by Faraz1243** [comment]
ok

**Comment by kushagra10bansal** [comment]
hey! @Faraz1243 could you please describe and assign me this task?

**Comment by Faraz1243** [comment]
This task is already completed. If you want to contribute, then create issue and mention what needs to be added. I'll add hacktoberfest label and assign it to you
