### ISSUE TITLE
Postfix to infix expression conversion

### ISSUE THREAD

**Issue by Ash0069** [Faraz1243/OpenSourse-Static-Web-Templates#60]
Using c

**Comment by Ash0069** [comment]
@Faraz1243 please assign this to me

**Comment by Faraz1243** [comment]
ok

**Comment by Faraz1243** [comment]
> @Faraz1243 please assign this to me

KIndly add all the code in the C++ functions file and don't create a new file

**Comment by prince9084yadav** [comment]
@Faraz1243 I have this code. Please assign it to me.

**Comment by Sayan115** [comment]
@Ash0069 kindly assign this to me
